title: "Adriano Soares"
url: "https://your-github-username.github.io"
description: "Explore the latest tech projects and interactive systems by Adriano Soares, a Software Engineer passionate about AI and full-stack development."
baseurl: "/"
