title: "Adriano Soares"
url: "https://adr1an0s0ar3s.github.io"
description: "Explore the latest tech projects and interactive systems by Adriano Soares, a Software Engineer passionate about AI and full-stack development."
baseurl: "/"
