title: "Adriano Soares"
url: "https://www.adrianosoares.com"
description: "Explore the latest tech projects and interactive systems by Adriano Soares, a Software Engineer passionate about AI and full-stack development."
baseurl: "/"
